image: Visual Studio 2017

before_build:
- choco install opencover.portable
- choco install codecov
- choco install firebird --version 2.5.7.1000
- copy "C:\\Program Files\\Firebird\\Firebird_2_5\\examples\\empbuild\\EMPLOYEE.FDB" .\employee.fdb

install:
- echo {"Database":{"ConnectionString":"User=SYSDBA;Password=masterkey;Database=%CD:\=\\%\\employee.fdb;DataSource=localhost;Port=3050;Dialect=3;Charset=NONE;Role=;Connection lifetime=15;Pooling=false;Packet Size=8192;ServerType=0;"}}>FirebirdSql.Metadata.Comparer.Tests/appsettings.json
- dotnet restore

test_script:
- OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test FirebirdSql.Metadata.Comparer.Tests/FirebirdSql.Metadata.Comparer.Tests.csproj --logger=trx" -filter:"+[FirebirdSql.Metadata.*]* -[FirebirdSql.Metadata.Comparer.Tests]*" -oldstyle -output:"coverage.xml"
- codecov -f "coverage.xml"
