language: csharp
solution: FirebirdSql.Metadata.Comparer.sln
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - dotnet restore
 - dotnet build
 - dotnet test FirebirdSql.Metadata.Comparer.Tests/FirebirdSql.Metadata.Comparer.Tests.csproj
