language: csharp
solution: FirebirdSql.Metadata.Comparer.sln
mono: none
dotnet: 2.0.0
dist: trusty
install:
 - dotnet restore
script:
 - dotnet build
after_success:
 - dotnet test FirebirdSql.Metadata.Comparer.Tests/FirebirdSql.Metadata.Comparer.Tests.csproj --logger "trx;LogFileName=testResults.trx"
