language: csharp
solution: FirebirdSql.Metadata.Comparer.sln
mono: none
dotnet: 2.0.0
dist: trusty
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y firebird2.5-superclassic firebird2.5-examples
 - sudo gunzip /usr/share/doc/firebird2.5-examples/examples/empbuild/employee.fdb.gz
install:
 - sudo cp /usr/share/doc/firebird2.5-examples/examples/empbuild/employee.fdb ./
 - sudo chown firebird.firebird employee.fdb
 - dotnet restore
 -  echo $'{"Database":{"ConnectionString":"User=SYSDBA;Password=masterkey;Database='${PWD}'/employee.fdb;DataSource=localhost;Port=3050;Dialect=3;Charset=NONE;Role=;Connection lifetime=15;Pooling=false;Packet Size=8192;ServerType=0;"}}'>FirebirdSql.Metadata.Comparer.Tests/appsettings.json
script:
 - dotnet build
after_success:
 - dotnet test FirebirdSql.Metadata.Comparer.Tests/FirebirdSql.Metadata.Comparer.Tests.csproj
