language: csharp
solution: FirebirdSql.Metadata.Comparer.sln
mono: none
dotnet: 2.0.0
dist: trusty
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y firebird2.5-superclassic firebird2.5-examples
 - sudo gunzip /usr/share/doc/firebird2.5-examples/examples/empbuild/employee.fdb.gz
 - sudo cp /usr/share/doc/firebird2.5-examples/examples/empbuild/employee.fdb ./
 - sudo chown firebird.firebird employee.fdb
install:
 - dotnet restore
script:
 - dotnet build
after_success:
 - dotnet test FirebirdSql.Metadata.Comparer.Tests/FirebirdSql.Metadata.Comparer.Tests.csproj
