using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace FirebirdSql.Metadata.Comparer.Lib.RDBModel.Entities
{
    /// <summary>
    /// RDB$RELATION_CONSTRAINTS stores the definitions of all table-level constraints: primary, unique, foreign key, CHECK, NOT NULL constraints.
    /// <see href="https://firebirdsql.org/file/documentation/reference_manuals/fblangref25-en/html/fblangref-appx04-relconstr.html"/>
    /// </summary>
    public class RdbRelationConstraint
    {
        /// <summary>
        /// The name of the table-level constraint defined by the user, or otherwise automatically generated by the system
        /// </summary>
        [Key, MaxLength(31)]
        public string ConstraintName { get; set; }

        /// <summary>
        /// The name of the constraint type: PRIMARY KEY, UNIQUE, FOREIGN KEY, CHECK or NOT NULL
        /// </summary>
        [MaxLength(11)]
        public string ConstraintType { get; set; }

        /// <summary>
        /// The name of the table this constraint applies to
        /// </summary>
        [MaxLength(31)]
        public string RelationName { get; set; }

        /// <summary>
        /// Currently NO in all cases: Firebird does not yet support deferrable constraints
        /// </summary>
        [MaxLength(3)]
        public string Deferrable { get; set; }

        /// <summary>
        /// Currently NO in all cases
        /// </summary>
        [MaxLength(3)]
        public string InitiallyDeferred { get; set; }

        /// <summary>
        /// The name of the index that supports this constraint. For a CHECK or a NOT NULL constraint, it is NULL.
        /// </summary>
        [MaxLength(31)]
        public string IndexName { get; set; }
    }
}
